# Generated by Django 4.0.6 on 2022-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('emailad', models.EmailField(max_length=254)),
                ('mailsub', models.CharField(max_length=70)),
                ('mailtext', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
